site: Alex Wheeler | Graphic & Web Design

url: https://alexwheeler.ca
baseurl: 

collections:
  pages:
    output: true
    permalink: /:slug/
  posts:
    output: true
    permalink: /blog/:slug/
  projects:
    output: true
    permalink: /work/:slug/
  projects-fr:
    output: true
    permalink: /fr/travail/:slug/


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "projects-fr"
    values:
      layout: "project"

markdown: kramdown

future: true

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-compress-images

imageoptim:
  pngout: true
  svgo: false
  verbose: true
  allow_lossy: true

paginate: 6
paginate_path: "/blog/page:num/"

gallery_types:
  carousel: Carousel
  grid: Grid
grid_columns:
  two: Two
  three: Three
  four: Four
  