site: Alex Wheeler | Graphic & Web Design
title: alexwheeler.ca

url: alexwheeler.ca
baseurl: 

collections:
  pages:
    output: true
    permalink: /:slug/
  posts:
    output: true
    permalink: /blog/:slug/
  projects:
    output: true
    permalink: /work/:slug/
  projects-fr:
    output: true
    permalink: /fr/travail/:slug/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "projects-fr"
    values:
      layout: "project"

markdown: kramdown

future: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

pagination:
  enabled: true
  per_page: 12
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true

  categories: 
    layouts: 
       - 'category.html'
    title: 'Blog'
    permalink: '/blog/:cat'
    
    slugify:
      mode: raw
      cased: true

  collections:
    layouts: 
       - 'collection.html'
  tags:
    layouts: 
       - 'tag.html'
    title: ':tag'
    permalink: '/tags/:tag'

gallery_types:
  carousel: Carousel
  grid: Grid

grid_columns:
  two: Two
  three: Three
  four: Four

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

plugins:
- jekyll-autoprefixer
- jekyll-paginate-v2
- jekyll-admin
- coffee-script
- uglifier
- sass
- jekyll-autoprefixer

exclude:
  - 'node_modules'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'build.js'
  - 'package-lock.json'
  - 'package.json'