basic_settings:
  site_title: Alex Wheeler
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logo-white.png
  logo_width: 40

menu_settings:
  menu_items:
    - title: 'Work'
      url: '/work/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    
  menu_items_fr:
  - title: 'Travail'
    url: '/fr/travail/'
  - title: 'Blog'
    url: '/blog/'
  - title: 'À propos'
    url: '/fr/a-propos/'
  - title: 'Contact'
    url: '/fr/contact/'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: Graphic design and web development

grid_settings:
  overlay_opacity: 1
  grid_spacing: 10

index:
  en:
  fr: fr/

contact_settings:
  form_action: 'https://app.99inbound.com/api/e/w2_U9VE7'
  form_action_fr: 'https://app.99inbound.com/api/e/xAPVnAaV'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  contact_email: design@alexwheeler.ca

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: 'https://www.instagram.com/alexwheeler__/'
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#6C7A89'
  text_light_color: '#ABB7B7'
  accent_color: '#229aff'
  border_color: '#dddddd'
  overlay_background_color: '#F2784B'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#229aff'
  error_color: '#D64541'

font_settings:
  font_embed:
  title_font: '"brandon", sans-serif'
  body_font: '"brandon", sans-serif'
  regular_weight: 200
  bold_weight: 300

  site_title:
    small_size: 20
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0.1

  menu:
    small_size: 50
    medium_size: 15
    large_size: 17
    weight: 200
    letter_spacing: 2

  grid_item_title:
    small_size: 40
    medium_size: 40
    large_size: 45
    weight: 400
    letter_spacing: -0.02

  grid_item_subtitle:
    small_size: 12
    medium_size: 12
    large_size: 15
    weight: 200
    letter_spacing: 0.2

  h1:
    small_size: 60
    medium_size: 75
    large_size: 120
    weight: 600
    letter_spacing: -0.02
    line_height: 1.2

  h2:
    small_size: 35
    medium_size: 45
    large_size: 50
    weight: 500
    letter_spacing: -0.02
    line_height: 1

  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: -0.02
    line_height: 1.3

  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6

  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6

  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6

  p:
    small_size: 16
    medium_size: 18
    large_size: 20
    weight: 200
    letter_spacing: 0
    line_height: 1.4
    max_width: 1000

  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6

  buttons:
    weight: 300
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""