basic_settings:
  site_title: Alex Wheeler – Graphic & Web Design
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logo-white.png
  logo_width: 33

menu_settings:
  menu_items:
    - title: 'work'
      url: '/work'
    - title: 'blog'
      url: '/blog'
    - title: 'about'
      url: '/about/'
    - title: 'contact'
      url: '/contact'
    
  menu_items_fr:
  - title: 'Travail'
    url: '/fr/travail'
  - title: 'Blog'
    url: '/blog'
  #- title: 'À propos'
  #  url: '/fr/a-propos'
  - title: 'Contact'
    url: '/fr/contact'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: Graphic design and web development

index:
  en:
  fr: fr/



contact_settings:
  form_action: 'https://app.99inbound.com/api/e/w2_U9VE7'
  form_action_fr: 'https://app.99inbound.com/api/e/xAPVnAaV'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  contact_email: design@alexwheeler.ca



font_settings:

  blog_item_title:
    small_size: 40
    medium_size: 45
    large_size: 45
    weight: 400
    letter_spacing: -0.02

  blog_item_subtitle:
    small_size: 12
    medium_size: 13
    large_size: 15
    weight: 200
    letter_spacing: 0.2



  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 300
    letter_spacing: 0
    line_height: 1.6

  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6

  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 300
    letter_spacing: 0
    line_height: 1.6



  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.4

  buttons:
    weight: 300
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""