basic_settings:
  site_title: Alex Wheeler – Graphic & Web Design
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/logo-white.png
  logo_width: 33

menu_settings:
  menu_items:
    - title: 'work'
      url: '/work'
    - title: 'blog'
      url: '/blog'
    # - title: 'About'
    #  url: '/about/'
    - title: 'contact'
      url: '/contact'
    
  menu_items_fr:
  - title: 'Travail'
    url: '/fr/travail'
  - title: 'Blog'
    url: '/blog'
  #- title: 'À propos'
  #  url: '/fr/a-propos'
  - title: 'Contact'
    url: '/fr/contact'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: Graphic design and web development

grid_settings:
  overlay_opacity: 1
  grid_spacing: 30

index:
  en:
  fr: fr/

breakpoints:
  desktop: 1600px
  laptop: 1220px
  tabletl: 1024px
  tabletp: 768px
  phonel: 480px

contact_settings:
  form_action: 'https://app.99inbound.com/api/e/w2_U9VE7'
  form_action_fr: 'https://app.99inbound.com/api/e/xAPVnAaV'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  contact_email: design@alexwheeler.ca

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'

  text_dark_color: 'rgba(0,0,0,0.9)'
  text_medium_color: 'rgba(0,0,0,0.7)'
  text_light_color: 'rgba(0,0,0,0.4)'

  accent_color: '#229aff'
  border_color: '#dddddd'

  overlay_background_color: '#F2784B'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#229aff'
  error_color: '#D64541'

font_settings:
  font_embed:
  title_font: '"Brandon Grotesque", sans-serif'
  body_font: '"Roboto Mono", sans-serif'
  regular_weight: 300
  bold_weight: 400

  site_title:
    small_size: 20
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0.1

  menu:
    small_size: 50
    medium_size: 15
    large_size: 15
    weight: 200
    letter_spacing: 2
    small_padding: 1
    large_padding: 1.5

  blog_item_title:
    small_size: 40
    medium_size: 45
    large_size: 45
    weight: 400
    letter_spacing: -0.02

  blog_item_subtitle:
    small_size: 12
    medium_size: 13
    large_size: 15
    weight: 200
    letter_spacing: 0.2

  h1:
    small_size: 45
    medium_size: 75
    large_size: 100
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2

  h2:
    small_size: 30
    medium_size: 32
    large_size: 50
    weight: 600
    letter_spacing: 0
    line_height: 1

  h3:
    small_size: 20
    medium_size: 25
    large_size: 30
    weight: 400
    letter_spacing: 0.02
    line_height: 1.3

  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 400
    letter_spacing: 0
    line_height: 1.6

  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6

  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 400
    letter_spacing: 0
    line_height: 1.6

  p:
    small_size: 11
    medium_size: 13
    large_size: 14
    weight: 200
    letter_spacing: 0
    line_height: 1.6
    max_width: 1000

  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.4

  buttons:
    weight: 300
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""